### ISSUE TITLE
Magic Storage Crafting Interface and RecursiveCraft issue

### ISSUE THREAD

**Issue by kubson3824** [ExterminatorX99/MagicStorage#24]
I'm attempting to craft a simple item that requires the Crafting Interface to make a few steps using RecursiveCraft. For example, I'm making a Storage Unit and the only thing I'm missing is a Storage component, but I have all the things necessary. When I press "craft", I get this error message.

`[01:53:55] [1/WARN] [tML]: Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.ModLoader.ItemLoader.OnCraft(Item item, Recipe recipe)
   at RecursiveCraft.CompoundRecipe.OnCraft(Item item) in RecursiveCraft\CompoundRecipe.cs:line 100
   at Terraria.ModLoader.RecipeHooks.OnCraft(Item item, Recipe recipe)
   at MagicStorageExtra.CraftingGUI.TryCraft() in MagicStorageExtra\CraftingGUI.cs:line 1796
   at MagicStorageExtra.CraftingGUI.UpdateCraftButton() in MagicStorageExtra\CraftingGUI.cs:line 806
   at MagicStorageExtra.CraftingGUI.Update(GameTime gameTime) in MagicStorageExtra\CraftingGUI.cs:line 455
   at Terraria.ModLoader.ModHooks.PostUpdateInput()
   at Terraria.Main.DoUpdate_HandleInput()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at DMD<Terraria.Main::Update>(Main , GameTime )
   at DMD<DMD<Hook<Terraria.Main::Update>?53006314>?60788108::Hook<Terraria.Main::Update>?53006314>(Main , GameTime )
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.FNALaunch.Main(String[] args)`

Surprisingly, when I took out one of the crafting stations and put them back in, I could craft the item, as long as I was in the interface. After leaving it, I would have to repeat the process all over again.

Using mods:
`[
  "AlchemistNPC",
  "AutoTrash",
  "Azercadmium",
  "CalamityMod",
  "CalValEX",
  "ElementsAwoken",
  "Fargowiltas",
  "FargowiltasSouls",
  "Luiafk",
  "MagicStorageExtra",
  "MaxStackExtra",
  "Polarities",
  "RecipeBrowser",
  "Redemption",
  "SacredTools",
  "SpiritMod",
  "Split",
  "StarsAbove",
  "SubworldLibrary",
  "VeinMiner",
  "WingSlot",
  "FKBossHealthBar",
  "BossChecklist",
  "imkSushisMod",
  "imkSushisModAddOn",
  "WMITF",
  "Laugicality",
  "WebmilioCommons",
  "SOTS",
  "FargowiltasSoulsDLC",
  "RecursiveCraft"
]`

**Comment by ExterminatorX99** [comment]
Does the issue happen if you disable Mod of Redemption?

**Comment by kubson3824** [comment]
Yes, the issue is still there after disabling Redemption.

**Comment by ExterminatorX99** [comment]
Try the new version of RecursiveCraft

**Comment by kubson3824** [comment]
Works perfectly now, closing the issue
