### ISSUE TITLE
Cannot access disposed object

### ISSUE THREAD

**Issue by Jacklz** [ExterminatorX99/MagicStorage#9]
Hey, thanks for implementing my previous suggestion! I like the tweaks you added to it as well with the different colors. Great job.

Anyway, I encountered this error after reloading mods. I already had about less than 8 mods enabled and including your magic storage, and i exited my world to enable recipe browser. Did that, opened the storage heart and i got the "System.InvalidOperationException: Begin cannot be called again until End has been successfully called."
So i checked the log file and found this error:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Texture2D'.
   at Microsoft.Xna.Framework.Helpers.CheckDisposed(Object obj, IntPtr pComPtr)
   at Microsoft.Xna.Framework.Graphics.TextureCollection.set_Item(Int32 index, Texture value)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.RenderBatch(Texture2D texture, SpriteInfo[] sprites, Int32 offset, Int32 count)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Flush()
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.End()
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.DrawChildren(SpriteBatch spriteBatch)
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch)
   at MagicStorageExtra.StorageGUI.Draw(TEStorageHeart heart) in MagicStorageExtra\StorageGUI.cs:line 223
   at MagicStorageExtra.InterfaceHelper.DrawStorageGUI() in MagicStorageExtra\InterfaceHelper.cs:line 45
   at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf()
   at Terraria.UI.GameInterfaceLayer.Draw()
   at Terraria.Main.DrawInterface(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

A restart of tmodloader solved the issue. Not sure if this was just a coincidence from updating mods from the browser but i remember the original magic storage having a similar issue with Texture2D so i thought I'd report it here to let you know. I believe this is the same error that another user posted with the title "the old bug"

**Comment by ExterminatorX99** [comment]
Published new update. It should fix this
